TARGET_DISK="/dev/nvme0n1"
HOSTNAME=""
USERNAME="magicletur"
USER_PASSWORD="magicletur"       # Change before building!
ROOT_PASSWORD="magicletur"       # Change before building!
TIMEZONE="Europe/Paris"
LOCALE="en_US.UTF-8"
KEYMAP="us"
SWAP_SIZE="16G"
WIFI_SSID=""                   # WiFi SSID for live ISO + installed system (leave empty for Ethernet)
WIFI_PASSWORD=""               # WiFi password
